trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Nome do pool de agentes self-hosted

variables:
  imageName: 'riquez/comment-api'

steps:
- checkout: self
  displayName: 'Checkout code'
  persistCredentials: true

# Mover o conteúdo da subpasta 'comment-api' para o diretório raiz
- script: |
    echo Moving content from comment-api to root directory
    mkdir temp && cp -r comment-api/* temp && rm -rf * && mv temp/* . && rm -rf temp
  displayName: 'Move comment-api content to root directory'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

# Garantir que pip está instalado e atualizado
- script: |
    python -m ensurepip --upgrade
    python -m pip install --upgrade pip
  displayName: 'Ensure pip is installed and upgraded'

# Adicionar diretório de scripts do Python ao PATH e instalar dependências
- script: |
    set PATH=%PATH%;C:\Users\henri\Desktop\Docs\agent\_work\1\s\Scripts
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerHubConnection'  # Nome da conexão de serviço configurada para o Docker Hub
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
