trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'  # Nome do pool de agentes self-hosted

variables:
  imageName: 'riquez/comment-api'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

# Novo passo para garantir que pip está instalado
- script: |
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python get-pip.py
  displayName: 'Install pip'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover
  displayName: 'Run tests'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerHubConnection'  # Nome da conexão de serviço configurada para o Docker Hub
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
